### PR TITLE
zhop feature for retraction test

### PR DESCRIPTION
**Pull request by vector76**
Attempted to implement feature mentioned in #2 

(required an offline script to modify the template).

### CODE REVIEW

**Comment by teachingtechYT** [comment]
Unfortunately the proposed code won't achieve the purpose. The html side is fine but the ZHOP is not a static value to be substituted in the gcode. To do this we keep keep track of the the current layer height and then z hop up relative to this before z hopping back to the layer height afterwards.

**Comment by vector76** [comment]
Can you double check? I am switching to relative mode (G91) to achieve the zhop in the template to keep the replacement simple.. Most of the action occurs in retraction.js.

**Comment by teachingtechYT** [comment]
Indeed you are right, GitHub truncated the last file so I thought there was no proposed changes to the source gcode. My apologies.
Using relative movement mode is a more elegant way to solve the problem. I will test.

**Comment by teachingtechYT** [comment]
Just implemented this although not with this pull request. The credit goes to you for the elegant solution. I ended up having a single marker in the source gcode and adding the G91, z hop G1 movement, G90 through javascript only if the value was not 0. The user can change z hop over the sic segments which was my original planned implementation. Many thanks.

**Comment by vector76** [comment]
Cool. I don't need credit, just wanting to help.

This sort of tuning regimen with a test pattern generator is long overdue.  (I even contemplated making one myself.)  I am thrilled that it's finally being done, so thank you!

**Pull request closed without merging**
