### PR TITLE
Include missing settings in Settings summary

### PR DESCRIPTION
**Pull request by ChrisToxz**
Added some missing parameters such as Feedrate, Nozzle & Layer height settings

image

### CODE REVIEW

**Comment by pseudex** [comment]
Hi,
there is also the custom end-gcode missing. Would be nice to have this also included in this PR

**Comment by teachingtechYT** [comment]
The highlighted settings from the first post are set by the user. Therefore they cannot be included in that section.

**Comment by teachingtechYT** [comment]
@pseudex I've added that info to the first tab. Next time just create a feature request issue of your own. Your request was almost missed.

**Comment by ChrisToxz** [comment]
> EDIT: Just realised i misunderstood the post and this is indeed useful. I will have a closer look.

Its just adding some missing parameters in the output file. No changes in functionality, gcode or whatever.

@pseudex Will add and actually check all missing parameters.

**Pull request closed without merging**
